"""Ajout du champ mot_de_passe dans Utilisateur

Revision ID: 278e47796ba6
Revises: 037d9bd96685
Create Date: 2024-09-23 20:11:37.058577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278e47796ba6'
down_revision = '037d9bd96685'
branch_labels = None
depends_on = None


def upgrade():       
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),  # Utilise String au lieu de LargeBinary
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.LargeBinary(length=60),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
