"""Ajout du champ etablissement_id dans Calendrier

Revision ID: ad58bb54c5f3
Revises: 13316d478f8b
Create Date: 2024-09-25 15:45:02.910295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad58bb54c5f3'
down_revision = '13316d478f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendrier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee_academique', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('etablissement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'etablissement', ['etablissement_id'], ['id'])
        batch_op.drop_column('titre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendrier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titre', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etablissement_id')
        batch_op.drop_column('annee_academique')

    # ### end Alembic commands ###
