"""backref niveaux added to School class

Revision ID: adfef005641a
Revises: ee0b4b7db676
Create Date: 2024-10-04 07:49:27.083649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adfef005641a'
down_revision = 'ee0b4b7db676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etablissement', schema=None) as batch_op:
        batch_op.drop_column('niveau')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etablissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau', postgresql.ENUM('moyen', 'lycee', name='niveau_enum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
