"""Serie and Niveau classes added and link School to Level(s)

Revision ID: ee0b4b7db676
Revises: ad58bb54c5f3
Create Date: 2024-10-04 07:41:12.390250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0b4b7db676'
down_revision = 'ad58bb54c5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveau',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.Enum('moyen', 'lycee', name='niveau_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('libelle', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niveau_etablissement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'serie', ['serie_id'], ['id'])
        batch_op.drop_column('serie')

    with op.batch_alter_table('etablissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau', sa.Enum('moyen', 'lycee', 'moyen-lycee', name='niveau_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etablissement', schema=None) as batch_op:
        batch_op.drop_column('niveau')

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('serie_id')

    op.drop_table('niveau_etablissement')
    op.drop_table('serie')
    op.drop_table('niveau')
    # ### end Alembic commands ###
